name: iOSApp
packages:
    ViewInspector:
        url: https://github.com/nalexn/ViewInspector
        from: "0.9.2"
targets:
    iOSApp:
        type: application
        platform: iOS
        deploymentTarget: "13.0"
        sources: [iOSApp]
        settings:
            base:
                INFOPLIST_FILE: iOSApp/Info.plist
                ENTITLEMENTS_FILE: iOSApp/App.entitlements
                PRODUCT_BUNDLE_IDENTIFIER: com.codename.ios.app
        scheme:
            testTargets:
                - iOSAppTests
    iOSAppTests:
        type: bundle.unit-test
        platform: iOS
        deploymentTarget: "13.0"
        sources: [iOSAppTests]
        settings:
            base:
                INFOPLIST_FILE: iOSAppTests/Info.plist
        dependencies:
            - target: iOSApp
            - package: ViewInspector
