name: BasicApp
packages:
    ViewInspector:
        url: https://github.com/nalexn/ViewInspector
        version: "0.9.5"
    SnapshotTesting:
        url: https://github.com/pointfreeco/swift-snapshot-testing.git
        version: "1.11.0"
targets:
    BasicApp:
        type: application
        platform: iOS
        deploymentTarget: "14.0"
        sources: [App]
        settings:
            base:
                INFOPLIST_FILE: App/Info.plist
                ENTITLEMENTS_FILE: App/App.entitlements
                PRODUCT_BUNDLE_IDENTIFIER: com.codename.ios.basic.app
        scheme:
            testTargets:
                - BasicAppTests
            gatherCoverageData: true
    BasicAppTests:
        type: bundle.unit-test
        platform: iOS
        deploymentTarget: "14.0"
        sources:
            - path: AppTests
              excludes:
                - ReferenceImages/**
        settings:
            base:
                INFOPLIST_FILE: AppTests/Info.plist
        dependencies:
            - target: BasicApp
            - package: ViewInspector
            - package: SnapshotTesting
